[package]
name = "dpmsg_rust"
version = "2.2.2"
rust-version = "1.63.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]
path = "dpmsg/lib.rs"

[dependencies]
drawdance = { path = "../rust" }
once_cell = "1.18.0"
regex = "1.9.4"
