name: Build and Test

on:
  pull_request:
  push:
    branches:
      - '**'
    tags-ignore:
      # This tag is (re)created when a build on main succeeds, it'd be
      # pointless to trigger yet another build in response to it.
      - continuous
  schedule:
    # Every Monday and Thursday at 11:18 AM.
    - cron: '18 11 * * 1,4'

env:
  CARGO_TERM_COLOR: always
  CMAKE_COLOR_DIAGNOSTICS: ON
  CLICOLOR_FORCE: 1

jobs:
  test:
    name: ${{ matrix.cross_os || matrix.os }} ${{ matrix.bits }}bit Qt ${{ matrix.qt }}${{ matrix.cross_os && format(' on {0}', matrix.os) }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
        qt:
          - 5.15.8
        bits:
          - 64
          - 32

        # There's ways to deduplicate these includes, but any mistake causes
        # utterly confounding errors, so just explicitly specify each target.
        include:
          - os: windows-latest
            qt: 5.15.8
            bits: 64
            sccache_triplet: x86_64-pc-windows-msvc
            build_flags: -DBUILD_PACKAGE_SUFFIX=64bit -G Ninja
            qt_pre_build: >
              choco install gperf jom winflexbison3 &&
              New-Item -Path C:\ProgramData\Chocolatey\bin\flex.exe -ItemType SymbolicLink -Value C:\ProgramData\Chocolatey\bin\win_flex.exe &&
              New-Item -Path C:\ProgramData\Chocolatey\bin\bison.exe -ItemType SymbolicLink -Value C:\ProgramData\Chocolatey\bin\win_bison.exe
            # Copying files is a disgusting hack because windeployqt does not
            # search PATH to find DLLs and it gets confused by QtKeychain having
            # a Qt prefix and thinks it is part of Qt and tries to process it
            # and fails if it is not in the Qt bin directory with the rest of
            # them
            packager: >
              cp .github/deps/other/bin/qt*.dll .github/deps/qt/bin &&
              cpack --verbose --config build/CPackConfig.cmake -C Release

          - os: windows-latest
            qt: 5.15.8
            bits: 32
            sccache_triplet: x86_64-pc-windows-msvc
            build_flags: -DCARGO_TRIPLE=i686-pc-windows-msvc -DBUILD_PACKAGE_SUFFIX=32bit -G Ninja
            qt_pre_build: >
              choco install gperf jom winflexbison3 &&
              New-Item -Path C:\ProgramData\Chocolatey\bin\flex.exe -ItemType SymbolicLink -Value C:\ProgramData\Chocolatey\bin\win_flex.exe &&
              New-Item -Path C:\ProgramData\Chocolatey\bin\bison.exe -ItemType SymbolicLink -Value C:\ProgramData\Chocolatey\bin\win_bison.exe
            # Copying files is a disgusting hack because windeployqt does not
            # search PATH to find DLLs and it gets confused by QtKeychain having
            # a Qt prefix and thinks it is part of Qt and tries to process it
            # and fails if it is not in the Qt bin directory with the rest of
            # them
            packager: >
              cp .github/deps/other/bin/qt*.dll .github/deps/qt/bin &&
              cpack --verbose --config build/CPackConfig.cmake -C Release

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # for git-describe
          submodules: true

      - name: Activate MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: win${{ matrix.bits }}
        if: runner.os == 'Windows'

      - name: Install NASM for building OpenSSL in Windows
        uses: ilammy/setup-nasm@v1
        with:
          platform: win${{ matrix.bits }}
        if: runner.os == 'Windows'

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x${{ matrix.bits }}
        if: runner.os == 'Windows'

      - name: Work around QTBUG-112465
        run: |
          # Moving directories is faster than deleting everything inside them
          mv ${ANDROID_SDK_ROOT}/platforms/{android-*-*,..}
          ls "${ANDROID_SDK_ROOT}/platforms"
        shell: bash
        if: matrix.cross_os == 'Android'

      - name: Configure Linux system dependencies
        uses: ./.github/actions/restore-linux
        if: runner.os == 'Linux'

      - name: Build dependencies
        uses: ./.github/actions/build-deps
        id: deps
        with:
          cache_key: ${{ runner.os }}${{ matrix.bits == 32 && '32' || '' }}
          path: .github/deps
          target_bits: "${{ matrix.bits }}"
          qt: ${{ matrix.qt }}
          qt_pre_build: ${{ matrix.qt_pre_build }}
          qt_args: ${{ matrix.qt_args }}
          other_pre_build: ${{ matrix.other_pre_build }}
          other_args: ${{ matrix.other_args }}
        if: '!matrix.cross_os'

      - name: Build cross-compiler dependencies
        uses: ./.github/actions/build-deps
        id: cross-deps
        with:
          cache_key: ${{ runner.os }}+${{ matrix.cross_os }}${{ matrix.bits == 32 && '32' || '' }}
          path: .github/cross-deps
          target_bits: "${{ matrix.bits }}"
          qt: ${{ matrix.qt }}
          qt_pre_build: ${{ matrix.cross_qt_pre_build }}
          qt_args: ${{ matrix.cross_qt_args }}
          other_pre_build: ${{ matrix.cross_other_pre_build }}
          other_args: ${{ matrix.cross_other_args }}
        if: matrix.cross_os

      - name: Set up compiler cache
        uses: ./.github/actions/pre-sccache
        id: sccache
        with:
          triplet: ${{ matrix.sccache_triplet }}
          cache_key: ${{ runner.os }}${{ matrix.bits == 32 && '32' || '' }}${{ matrix.cross_os && format('+{0}', matrix.cross_os) }}-${{ matrix.qt }}

      - name: Cache gradle
        uses: actions/cache@v3
        with:
          # The zip file is unnecessary but the .zip.ok file is needed or it
          # will blow away the installation and redownload everything
          path: |-
            ~/.gradle/wrapper/dists/gradle-*/*/gradle-*
            !~/.gradle/wrapper/dists/gradle-*/*/gradle-*.zip
          key: gradle-${{ runner.os }}${{ matrix.bits == 32 && '32' || '' }}+${{ matrix.cross_os }}-${{ matrix.qt }}
        if: matrix.cross_os == 'Android'

      - name: Install Android 64 bit Rust target
        run: >
          rustup target add aarch64-linux-android
        if: matrix.cross_os == 'Android' && matrix.bits == 64

      - name: Install Android 32 bit Rust target
        run: >
          rustup target add armv7-linux-androideabi
        if: matrix.cross_os == 'Android' && matrix.bits == 32

      - name: Prepare Windows signing
        run: |
          if ($env:WINDOWS_CERTIFICATE) {
            New-Item -ItemType directory -Path "$env:GITHUB_WORKSPACE/wincert"
            Set-Content -Path "$env:GITHUB_WORKSPACE/wincert/drawpile.txt" -Value $env:WINDOWS_CERTIFICATE
            certutil -decode "$env:GITHUB_WORKSPACE/wincert/drawpile.txt" "$env:GITHUB_WORKSPACE/wincert/drawpile.pfx"
            Remove-Item -Path "$env:GITHUB_WORKSPACE/wincert/drawpile.txt"
            echo "WINDOWS_PFX_PATH=$env:GITHUB_WORKSPACE/wincert/drawpile.pfx" >>$env:GITHUB_ENV
          }
        env:
          WINDOWS_CERTIFICATE: ${{ secrets.WINDOWS_CERTIFICATE }}
        if: runner.os == 'Windows'

      - name: Generate project
        run: >
          cmake -S . -B build --log-level=VERBOSE
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_C_COMPILER_LAUNCHER=sccache
          -DCMAKE_CXX_COMPILER_LAUNCHER=sccache
          -DCMAKE_OBJC_COMPILER_LAUNCHER=sccache
          -DCMAKE_OBJCXX_COMPILER_LAUNCHER=sccache
          -DCLIENT=on
          -DSERVER=off
          -DSERVERGUI=off
          -DTOOLS=off
          -DTESTS=on
          -DUSE_GENERATORS=off
          "-DCMAKE_PREFIX_PATH=${{ matrix.cross_os && format('{0};', steps.cross-deps.outputs.path) }}${{ steps.deps.outputs.path }}"
          -DCMAKE_INSTALL_PREFIX=out
          -DCLANG_TIDY=off
          -DDIST_BUILD=${{ matrix.packager && 'on' }}
          -DSOURCE_ASSETS=off
          -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=on
          -DBUILD_VERSION=2.2.1
          ${{ matrix.build_flags }}

      - name: Prepare APK signing
        run: |
          if [ -n "$ANDROID_KEYSTORE" ] && [ -n "$ANDROID_KEYSTORE_PASS" ]; then
            keystore_path="$GITHUB_WORKSPACE/drawpile.keystore"
            echo "$ANDROID_KEYSTORE" | base64 -d > "$keystore_path"
            echo QT_ANDROID_KEYSTORE_PATH="$keystore_path" >> "$GITHUB_ENV"
          fi
        env:
          ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
          ANDROID_KEYSTORE_PASS: ${{ secrets.ANDROID_KEYSTORE_PASS }}
        if: matrix.cross_os == 'Android' && matrix.packager

      - name: Build project
        run: cmake --build build --parallel $(nproc || sysctl -n hw.ncpu || echo 2) --config Release
        env:
          RUSTC_WRAPPER: sccache
          SCCACHE_CACHE_SIZE: 200M
          SCCACHE_DIR: ${{ steps.sccache.outputs.path }}/cache
          QT_ANDROID_KEYSTORE_ALIAS: drawpile
          QT_ANDROID_KEYSTORE_STORE_PASS: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          WINDOWS_PFX_PASS: ${{ secrets.WINDOWS_CERTIFICATE_PASS }}
          WINDOWS_PFX_TIMESTAMP_URL: 'http://timestamp.digicert.com'

      - name: Run C++ tests
        run: ctest -C Release --output-on-failure
        working-directory: build
        if: '!matrix.cross_os'

      - name: Run packaging
        run: ${{ matrix.packager }}
        env:
          WINDOWS_PFX_PASS: ${{ secrets.WINDOWS_CERTIFICATE_PASS }}
          WINDOWS_PFX_TIMESTAMP_URL: 'http://timestamp.digicert.com'
        if: matrix.packager

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: matrix.packager
        with:
          name: Drawpile-${{ matrix.cross_os || runner.os }}-${{ matrix.bits }}bit-Qt${{ matrix.qt }}
          path: |
            Drawpile-*.AppImage
            Drawpile-*.apk
            Drawpile-*.dmg
            Drawpile-*.msi
            Drawpile-*.zip

      - name: Upload error logs and artefacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: ${{ matrix.cross_os || runner.os }} error logs and artefacts
          path: |
            **/*.log
            **/*.wxs

      - name: Save sccache
        uses: ./.github/actions/post-sccache
        with:
          cache-hit: ${{ steps.sccache.outputs.cache-hit }}
          cache_key: ${{ steps.sccache.outputs.cache_key }}
        if: success() || failure()
        continue-on-error: true

      - name: sccache stats
        run: sccache --show-stats
        if: success() || failure()
        continue-on-error: true

  release:
    needs: test
    runs-on: ubuntu-20.04
    if: >
      success() && (
          github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
          || startsWith(github.ref, 'refs/tags/'))
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Dump directory contents
        run: ls -alFR

      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: checkout

      - name: Collect release notes
        if: startsWith(github.ref, 'refs/tags/')
        run: awk -v RS='' '/^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2} Version ${{ github.ref_name }}/,/^[[:digit:]]/' checkout/ChangeLog | tail '+2' > release-description

      - name: Write continuous release description
        if: "!startsWith(github.ref, 'refs/tags/')"
        env:
          RELEASE_DESCRIPTION: >
            This release is an automatically generated snapshot of the current
            state of development. It is continuously updated with
            work-in-progress changes that may be broken, incomplete, or
            incompatible with other versions of Drawpile. For downloads, take a
            look at the Assets below.


            Unless you really, really know what you're doing, **pick the 64bit
            options**. 32bit is probably *not* what you want unless you have a
            very strange device.
        run:
          echo "$RELEASE_DESCRIPTION" > release-description

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_COMMIT: ${{ github.sha }}
          RELEASE_DESCRIPTION_FILE: release-description
          RELEASE_NAME: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || 'continuous' }}
          CLOBBER_EXISTING: ${{ !startsWith(github.ref, 'refs/tags/') }}
          PRERELEASE: ${{ !startsWith(github.ref, 'refs/tags/') || contains(github.ref, '-') }}
        run: |
          checkout/pkg/make-github-release.sh \
            'Drawpile-Android-64bit-Qt5.15.8;Drawpile-*.apk;Android APK 64bit' \
            'Drawpile-Linux-64bit-Qt5.15.8;Drawpile-*.AppImage;Linux AppImage 64bit' \
            'Drawpile-macOS-64bit-Qt5.15.8;Drawpile-*.dmg;macOS Disk Image' \
            'Drawpile-Windows-64bit-Qt5.15.8;Drawpile-*.msi;Windows Installer 64bit' \
            'Drawpile-Windows-64bit-Qt5.15.8;Drawpile-*.zip;Windows Portable ZIP 64bit' \
            'Drawpile-Android-32bit-Qt5.15.8;Drawpile-*.apk;Android APK 32bit - do not use, you want 64bit' \
            'Drawpile-Windows-32bit-Qt5.15.8;Drawpile-*.msi;Windows Installer 32bit - do not use, you want 64bit' \
            'Drawpile-Windows-32bit-Qt5.15.8;Drawpile-*.zip;Windows Portable ZIP 32bit - do not use, you want 64bit'
